### ISSUE TITLE
Implement OpenID Connect Protocol 

### ISSUE THREAD

**Issue by eliasjpr** [eliasjpr/authly#2]
Implement Open ID connect protocol on top of OAuth 2. 

**Requirements:**
- Follow the requirements found here https://openid.net/developers/specs/

**Comment by itsezc** [comment]
@eliasjpr Any (planned) updates on this?

**Comment by eliasjpr** [comment]
@itsezc feel free to add support for it and open a PR. Not sure when I will be able to dedicate time to this

**Comment by eliasjpr** [comment]
@itsezc this has been implemented in v1
