### ISSUE TITLE
Add support for the PKCE extension

### ISSUE THREAD

**Issue by BlobCodes** [eliasjpr/authly#5]
**Is your feature request related to a problem? Please describe.**
First off: Thanks for creating this library!
Because I want to create an application which native clients should authenticate from, it'd be very important for the security to have the PKCE extension included. (The latest OAuth Security BCP now recommends using PKCE also for server-side apps, as it provides some additional benefits there as well.)

**Describe the solution you'd like**
Implement PKCE

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by eliasjpr** [comment]
@BlobCodes thanks for opening this issue. Is going to take me some time before I can work on this change. I was wondering if you would like to either put an quick PR and we can discuss the implementation. I can hop on a hangout call if that would help

**Comment by eliasjpr** [comment]
@BlobCodes still interested in helping with this requirement?

**Comment by BlobCodes** [comment]
@eliasjpr I currently don't really have time to code, I'll reach out to you when I'm able to help!

**Comment by eliasjpr** [comment]
@BlobCodes this has been implemented in v1
